spring.application.name=livetrack

spring.datasource.url=jdbc:postgresql://localhost:5432/livetrack
spring.datasource.username=postgres
spring.datasource.password=manager
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
